/*
* Copyright (C) 2019 ~ 2019 UnionTech Software Technology Co.,Ltd.
*
* Author:     leilong <dshadow@foxmail.com>
*
* Maintainer: leilong <dshadow@foxmail.com>
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.fcitx.littlesun.xml -i widget.h -a keyboardAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "keyboardAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServerAdaptor
 */

ServerAdaptor::ServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerAdaptor::~ServerAdaptor()
{
    // destructor
}

int ServerAdaptor::hideView()
{
    // handle method call com.fcitx.littlesun.server.hideView
    int out0;
    QMetaObject::invokeMethod(parent(), "hideView", Q_RETURN_ARG(int, out0));
    return out0;
}

int ServerAdaptor::initView()
{
    // handle method call com.fcitx.littlesun.server.initView
    int out0;
    QMetaObject::invokeMethod(parent(), "initView", Q_RETURN_ARG(int, out0));
    return out0;
}

int ServerAdaptor::showView()
{
    // handle method call com.fcitx.littlesun.server.showView
    int out0;
    QMetaObject::invokeMethod(parent(), "showView", Q_RETURN_ARG(int, out0));
    return out0;
}

