/*
*
* Author:     leilong <dshadow@foxmail.com>
*
*/
/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.fcitx.littlesun.xml -i widget.h -a keyboardAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "keyboardAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServerAdaptor
 */

ServerAdaptor::ServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerAdaptor::~ServerAdaptor()
{
    // destructor
}

int ServerAdaptor::hideView()
{
    // handle method call com.fcitx.littlesun.server.hideView
    int out0;
    QMetaObject::invokeMethod(parent(), "hideView", Q_RETURN_ARG(int, out0));
    return out0;
}

int ServerAdaptor::initView()
{
    // handle method call com.fcitx.littlesun.server.initView
    int out0;
    QMetaObject::invokeMethod(parent(), "initView", Q_RETURN_ARG(int, out0));
    return out0;
}

int ServerAdaptor::showView()
{
    // handle method call com.fcitx.littlesun.server.showView
    int out0;
    QMetaObject::invokeMethod(parent(), "showView", Q_RETURN_ARG(int, out0));
    return out0;
}

